# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f12ff09d4e91f623194398d513d212a4d5b5047225178a436e5c995240318f0375ec121f43cfc37ab8232d1ae69bcba2c9a08b0e4827d34f00211098edbfcf53

test:
  secret_key_base: 19ce9695273d26b2a4fd4187c4ef73eb91199e499c501d74295f113715513bf96dbeabf49dbb499b3f234f8b24dce5aed9192de54060edc2c96d856446e1dcae

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
